### PR TITLE
Provided support for multilevel JSON structures, applying appropriate section levels

### PR DESCRIPTION
**Pull request by hdamron17**
Run `sh create_total.sh GeeksForGeeks` for the full through process to PDF or apply each section individually accordingly with the script.

* `total_json.sh` combines everything in the JSON directory into a single JSON file in TOTAL_JSON
* `download_all.py` splits the large JSON file and runs each section independently through `download_html.py`; combines the html outputs into a single html file in the HTML directory
* Can then run `html_to_pdf.py` as usual on the resulting large html file

### CODE REVIEW

**Comment by dufferzafar** [comment]
Just to see if I'm understanding this clearly - this allows you to create a single massive PDF of all the topics?

What does the Table of Contents even look like in such a case?

**Comment by hdamron17** [comment]
Yes, that is the goal. It will create a very long table of contents but I am using it as reference material for a coding competition which only allows paper notes so this is desirable in my case. The main advantage of this for the general user, though, is that it allows a more navigable table of contents. I have attached the output of the sample document which shows how the table of contents will look.

[GeeksForGeeksSample.pdf](https://github.com/dufferzafar/geeksforgeeks.pdf/files/2518991/GeeksForGeeksSample.pdf)

Unfortunately, I am realizing now that it had issues for the entire document, so I will need to debug that before this can be merged. It did not give any error messages but the output document did not exist, so I am curious if it is just too massive for pandoc. I will let you know when I resolve this, if you are interested.

**Comment by dufferzafar** [comment]
> I will let you know when I resolve this, if you are interested.

Yeah, and I'll be happy to merge this!

The PDF does look clean.

**Comment by hdamron17** [comment]
I have pushed the now working code. It rearranged the directory structure a bit from before, now producing intermediate TeX files for each topic and then just a bunch of \input statements in the main file to improve reusability of topic TeX files. I also had to blacklist about 5 pages because of invalid characters or figures. The final product is quite large (43089 pages) so the sample I sent before will have to suffice.

**Pull request merged**
